package database

const (
	ProfileId                = "id"
	ProfileShardingFirst     = "sharding_first"
	ProfileShardingLast      = "sharding_last"
	ProfileShardingSeparator = "sharding_separator"
	ProfileWrite             = "write"
	ProfileRead              = "read"
	ProfileBackup            = "backup"
	ProfileHost              = "host"
	ProfileUsername          = "username"
	ProfilePassword          = "password"
	ProfileDriver            = "driver"
	ProfileProto             = "proto"
	ProfilePort              = "port"
	ProfileDatabase          = "database"
	ProfileCharset           = "charset"
	ProfileCollation         = "collation"
	ProfileTimeout           = "timeout"
	ProfileMaxOpen           = "max_open"
	ProfileMaxIdle           = "max_idle"
	ProfileMaxLifetime       = "max_lifetime"
	ProfileDsn               = "dsn"
)
